# Generated by Django 5.0.3 on 2024-03-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Date add')),
                ('stars', models.PositiveIntegerField(verbose_name='Stars')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Text')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productmodel', verbose_name='Product')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofilemodel', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
